const etymologyData = [
    { word: "Ampersand", story: "Contraction of and per se and, meaning the character '&' by itself is 'and'. The symbol is based on the Latin word et \"and,\" and comes from an old Roman system of shorthand signs (ligatures)", year: "1797", category: [], imageUrl: "" },
    { word: "Ammonia", story: "the gas obtained from sal ammoniac, salt deposits containing ammonium chloride found near temple of Jupiter Ammon in Libya (coined in scientific Latin 1782)", year: "1782", category: [], imageUrl: "https://images.nypl.org/index.php?id=81583&t=w" },
    { word: "Bikini", story: "Named after Bikini Atoll, an island where an atom bomb was exploded in 1946 (coined 1947, after the test).", year: "1947", category: ["proper-noun"], imageUrl: "" },
    { word: "Clue", story: "Revised spelling off clew (a ball of thread or yarn); Given by Ariadne to Theseus as a guide out of the Labyrinth. Spelling 'clue' first seen 1400s.", year: "1400s", category: [], imageUrl: "" },
    { word: "Curfew", story: "From cuevre (to cover) + feu (fire); Medieval practice to bank hearths at a bell.", year: "1300s", category: [], imageUrl: "" },
    { word: "Jinx", story: "Probably a variant of jynx ‘wryneck’ (bird used in witchcraft).", year: "1690s", category: [], imageUrl: "" },
    { word: "Hamburger", story: "Food stands in NYC harbor served “steak cooked in the Hamburg style” to attract German sailors.", year: "1700s", category: ["proper-noun", "food"], imageUrl: "" },
    { word: "Hysteria", story: "From Greek hystera (womb); Originally a neurotic condition peculiar to women thought caused by uterus dysfunction.", year: "1801", category: [], imageUrl: "" },
    { word: "Ketchup", story: "Possibly from Tulu kajipu (curry) or Malay kichap (fish sauce). Term first appeared 1682.", year: "1682", category: ["food"], imageUrl: "" },
    { word: "Mandarin", story: "Used for 'Chinese official,' from Sanskrit ‘mantri’ (minister).", year: "1580s", category: [], imageUrl: "" },
    { word: "Macabre", story: "Reference to ‘the dance of the Maccabees’ (Jewish revolt leaders' martyrdom). Earliest use early 15c.", year: "1400s", category: ["proper-noun"], imageUrl: "" },
    { word: "Muscle", story: "From Latin musculus (little mouse); Shape/movement of some muscles thought to resemble mice.", year: "1300s", category: [], imageUrl: "" },
    { word: "Nickname", story: "From Middle English nekename, alteration of earlier ekename (additional name) attested 1303.", year: "1303", category: [], imageUrl: "" },
    { word: "Pupil", story: "From Latin pūpilla (pupil, little girl); Named for small reflected image in the eye.", year: "", category: [], imageUrl: "" },
    { word: "Sabotage", story: "From French saboter (to walk noisily, from sabot 'wooden shoe'); Reference to labor disputes.", year: "1903", category: [], imageUrl: "" },
    { word: "Sabbatical", story: "From Greek sabbatikos (of the Sabbath); Suggested by sabbatical year in Mosaic law.", year: "1590s", category: [], imageUrl: "" },
    { word: "Serendipity", story: "Coined by Horace Walpole, suggested by 'The Three Princes of Serendip' fairy tale.", year: "1754", category: ["proper-noun"], imageUrl: "" },
    { word: "Sinister", story: "From Latin sinister (left, on the left side) opposite of dexter.", year: "", category: [], imageUrl: "" },
    { word: "Tragedy", story: "From Greek tragos (goat) + ōidē (song); The connection with goats may be via satyric drama, from which tragedy later developed, in which actors or singers were dressed in goatskins to represent satyrs.", year: "1530s", category: [], imageUrl: "" },
    { word: "Vernacular", story: "From verna (slave born in the master's house).", year: "", category: [], imageUrl: "" },
    { word: "Vulgar", story: "From Latin vulgaris, from vulgus (common people).", year: "", category: [], imageUrl: "" },
    { word: "Volcano", story: "From Latin Vulcanus, Roman god of fire.", year: "", category: ["proper-noun"], imageUrl: "" },

    // Unlikely Couples
    { word: "Helicopter", story: "With Pterodactyl. Greek: helico (spiral) + pter (one with wings). Adopted from French 1861.", year: "1861", category: ["couplet"], coupletId: "helicopter-pterodactyl", imageUrl: "" },
    { word: "Pterodactyl", story: "With Helicopter. An extinct flying reptile: pter (one with wings) + dactylos (finger).", year: "", category: ["couplet"], coupletId: "helicopter-pterodactyl", imageUrl: "" },
    { word: "Pomegranate", story: "With Grenade. Latin pomum granatum 'apple with many seeds'.", year: "", category: ["couplet", "food"], coupletId: "pomegranate-grenade", imageUrl: "" },
    { word: "Grenade", story: "With Pomegranate. Weapon named as it resembled the fruit. First English use 1590s.", year: "1590s", category: ["couplet", "food"], coupletId: "pomegranate-grenade", imageUrl: "" },
    { word: "Orchids", story: "With Avocado. Greek órchis (testicle); Describes appearance of plant's tubers. Term 'orchid' introduced 1845.", year: "1845", category: ["couplet"], coupletId: "orchids-avocado", imageUrl: "" },
    { word: "Avocado", story: "With Orchids. Spanish from Nahuatl meaning testicle. Name used in English since 1764.", year: "1764", category: ["couplet", "food"], coupletId: "orchids-avocado", imageUrl: "" },
    { word: "Fungus", story: "With Sponge. From Greek sphongos (sponge) the Attic form of spongos.", year: "1527", category: ["couplet"], coupletId: "fungus-sponge", imageUrl: "" },
    { word: "Sponge", story: "With Fungus. From Greek sphongos (sponge).", year: "", category: ["couplet"], coupletId: "fungus-sponge", imageUrl: "" },
    { word: "Chaos", story: "With Yawn. Greek khaos (abyss). Used in English since late 14c.", year: "1300s", category: ["couplet"], coupletId: "chaos-yawn", imageUrl: "" },
    { word: "Yawn", story: "With Yawn. From Greek root ghieh- to yawn.", year: "", category: ["couplet"], coupletId: "chaos-yawn", imageUrl: "" },
    { word: "Canvas", story: "With Cannabis. Old French chanevaz (literally, made of hemp). OED earliest evidence 1260.", year: "1260", category: ["couplet"], coupletId: "canvas-cannabis", imageUrl: "" },
    { word: "Cannabis", story: "With Canvas. From Greek kannabis (hemp) a Scythian or Thracian word.", year: "1728", category: ["couplet"], coupletId: "canvas-cannabis", imageUrl: "" },
    { word: "Gargoyle", story: "With Gargle. Possibly from garg (imitative of throat sounds) + goule (From Latin gula = throat).", year: "1200s", category: ["couplet"], coupletId: "gargoyle-gargle", imageUrl: "" },
    { word: "Gargle", story: "With Gargoyle. Old French gargole (throat).", year: "1527", category: ["couplet"], coupletId: "gargoyle-gargle", imageUrl: "" },

    // Proper Nouns
    { word: "Bougainvillaea", story: "French navigator Louis Bougainville posthumously in 1849.", year: "1849", category: ["proper-noun"], imageUrl: "" },
    { word: "Dunce", story: "Follower of John Duns Scotus. Term used for those rejecting new knowledge by 1530.", year: "1530", category: ["proper-noun"], imageUrl: "" },
    { word: "Luddite", story: "Name taken by weavers who destroyed machinery, from Ned Ludd. Name occurs in writings by 1811.", year: "1811", category: ["proper-noun"], imageUrl: "" },
    { word: "Sadism", story: "From Count Donatien A.F. de Sade. Term coined in 1886.", year: "1886", category: ["proper-noun"], imageUrl: "" },
    { word: "Masochism", story: "From Leopold von Sacher-Masoch. Term coined in 1886.", year: "1886", category: ["proper-noun"], imageUrl: "" },
    { word: "Sandwich", story: "Named after the Earl of Sandwich, who ate meat between bread while gambling.", year: "", category: ["proper-noun", "food"], imageUrl: "" }
    
];
