const etymologyData = [
    { word: "Ampersand",
     story: "Contraction of 'and per se and', meaning the character '&' by itself is 'and'. The symbol is based on the Latin word et \"and,\" and comes from an old Roman system of shorthand signs (ligatures).",
     year: "1797", category: [], imageUrl: "" },
    { word: "Ammonia",
     story: "Gas obtained from sal ammoniac, salt deposits containing ammonium chloride found near temple of Jupiter Ammon in Libya. Ammon is the Greek and Roman conception of the Egyptian sovereign sun-god Amun (said to mean literally 'hidden')",
     year: "1782", category: ["proper-noun"], imageUrl: "https://images.nypl.org/index.php?id=81583&t=w" },
    { word: "Bikini",
     story: "Named after Bikini Atoll, an island where an atom bomb was tested in 1946.",
     year: "1947", category: ["proper-noun"], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Operation_Crossroads_-_Able_001.jpg" },
    { word: "Clue",
     story: "Revised spelling off clew (a ball of thread or yarn); Given by Ariadne to Theseus as a guide out of the Labyrinth. Spelling 'clue' first seen 1400s.",
     year: "1400s", category: [], imageUrl: "https://pbs.twimg.com/media/DwUS7U4W0AAIZjz.jpg" },
    { word: "Curfew",
     story: "From cuevre (to cover) + feu (fire); Medieval practice to bank hearths at a bell.",
     year: "1300s", category: [], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Couvre-feu_utensil.jpg" },
    { word: "Jinx",
     story: "Probably a variant of jynx ‘wryneck’ (bird used in witchcraft).",
     year: "1690s", category: [], imageUrl: "https://cdn2.picryl.com/photo/1876/12/31/jynx-torquilla-1876-924a5b-1024.jpg" },
    { word: "Hamburger",
     story: "Food stands in NYC harbor served “steak cooked in the Hamburg style” to attract German sailors.the -burg is German for fort, in reference to the moated castle built there c. 825; the first element is perhaps Old High German hamma (ham, back of the knee) in a transferred sense of bend, angle, with reference to its position on a river bend promontory; or Middle High German hamme - enclosed area of pastureland.",
     year: "1700s", category: ["proper-noun", "food"], imageUrl: "https://nwcartographic.com/cdn/shop/products/12341a_1200x1200.jpg?v=1736980280" },
    { word: "Hysteria",
     story: "From Greek hystera (womb); Originally a neurotic condition peculiar to women thought caused by uterus dysfunction.",
     year: "1801", category: [], imageUrl: "" },
    { word: "Ketchup",
     story: "Possibly from Tulu kajipu (curry) or Malay kichap (fish sauce).",
     year: "1682", category: ["food"], imageUrl: "" },
    { word: "Mandarin",
     story: "Used for 'Chinese official,' from Sanskrit ‘mantri’ (minister).",
     year: "1580s", category: [], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Officials.jpeg" },
    { word: "Macabre",
     story: "Reference to ‘the dance of the Maccabees’ (Jewish revolt leaders' martyrdom). The name Maccabees derives from the Aramaic maqqəḇa (the hammer), in recognition of Judah's ferocity in battle. OR The traditional Jewish explanation is that Maccabee is an acronym for the Torah verse that was the battle-cry of the Maccabees, 'Mi kamocha ba'elim YHWH', 'Who is like You among the heavenly powers, oh God!",
     year: "1400s", category: ["proper-noun"], imageUrl: "https://cdn.prod.website-files.com/5b8fd783bee52c8fb59b1fac/639a137ac9795d11a82cff3e_mattisyahu-and-apostate.jpeg" },
    { word: "Meander",
     story: "From the name of the Maiandros (now the Büyük Menderes River) in Caria (Western Turkey) known for its extremely winding course.",
     year: "1600s", category: [], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Rio-cauto-cuba.JPG" },
    { word: "Muscle",
     story: "From Latin musculus (little mouse); Shape/movement of some muscles thought to resemble mice.",
     year: "1300s", category: [], imageUrl: "https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/2603311/5549959/apiissh2g__95895.1626315497.jpg" },
    { word: "Nickname",
     story: "From Middle English nekename, alteration of earlier ekename (additional name).",
     year: "1303", category: [], imageUrl: "" },
    { word: "Pupil",
     story: "From Latin pūpilla (pupil, little girl); Named for small reflected image in the eye.",
     year: "", category: [], imageUrl: "" },
    { word: "Sabotage",
     story: "From French saboter (to walk noisily, from sabot 'wooden shoe'); Reference to labor disputes.",
     year: "1903", category: [], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Henry_Ossawa_Tanner_-_The_Young_Sabot_Maker_-_Google_Art_Project.jpg/1280px-Henry_Ossawa_Tanner_-_The_Young_Sabot_Maker_-_Google_Art_Project.jpg" },
    { word: "Sabbatical",
     story: "From Greek sabbatikos (of the Sabbath), a term perhaps suggested by the sabbatical year in Mosaic law — the seventh year — in which land was to remain untilled and non-foreign debtors and slaves released.",
     year: "1590s", category: [], imageUrl: "" },
    { word: "Serendipity",
     story: "The Three Princes of Serendip is the English version of the Italian translation of the Persian fairy tale, adapted from Book One of Amir Khusrau's Hasht-Bihisht of 1302. Serendip is the Classical Persian name for Sri Lanka (Ceylon). The story is the source of the word serendipity, coined by Horace Walpole because of his recollection of the part of the 'silly fairy tale' in which the three princes by 'accidents and sagacity' discern the nature of a lost camel.",
     year: "1754", category: ["proper-noun"], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Seven_pavilions.jpg" },
    { word: "Sinister",
     story: "From Latin sinister (left, on the left side) opposite of dexter.",
     year: "", category: [], imageUrl: "" },
    { word: "Tragedy",
     story: "From Greek tragos (goat) + ōidē (song); The connection with goats may be via satyric drama, from which tragedy later developed, in which actors or singers were dressed in goatskins to represent satyrs.",
     year: "1530s", category: [], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/F13r-aberdeen-best.jpg/330px-F13r-aberdeen-best.jpg" },
    { word: "Vernacular",
     story: "From verna (slave born in the master's house).",
     year: "", category: [], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/ScanianLaw_B74.jpg" },
    { word: "Vulgar",
     story: "From Latin vulgaris, from vulgus (common people).",
     year: "", category: [], imageUrl: "https://cdn.cosmos.so/ff0da78e-a113-4cf6-baa9-2dd1248181ee?format=webp&w=1168" },
    { word: "Volcano",
     story: "From Latin Vulcanus, Roman god of fire.",
     year: "", category: ["proper-noun"], imageUrl: "https://api.nga.gov/iiif/47133e8d-e227-4e32-a69c-8a62775b2c72/full/!800,800/0/default.jpg" },

    // Unlikely Couples
    { word: "Helicopter", story: "Greek: helico (spiral) + pter (one with wings). (unlikely couple with Pterodactyl) ", year: "1861", category: ["couplet"], coupletId: "helicopter-pterodactyl", imageUrl: "" },
    { word: "Pterodactyl", story: "An extinct flying reptile: pter (one with wings) + dactylos (finger). (unlikely couple with Helicopter)", year: "", category: ["couplet"], coupletId: "helicopter-pterodactyl", imageUrl: "" },
    { word: "Pomegranate",
     story: "(unlikely couple with Grenade) Latin pomum granatum 'apple with many seeds'.",
     year: "", category: ["couplet", "food"], coupletId: "pomegranate-grenade", imageUrl: "https://cdn.cosmos.so/4f13ecad-e383-4fee-95a8-ab2b63c01fb9?format=webp&w=554" },
    { word: "Grenade",
     story: "(unlikely couple with Pomegranate) Weapon named as it resembled the fruit.",
     year: "1590s", category: ["couplet", "food"], coupletId: "pomegranate-grenade", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/31/Ming_Dynasty_fragmentation_bomb.jpg" },
    { word: "Orchids",
     story: "With Avocado. Greek órkhis (testicle); Describes appearance of plant's tubers.",
     year: "1845", category: ["couplet"], coupletId: "orchids-avocado", imageUrl: "https://hekint.org/wp-content/uploads/2023/01/301109m.jpg" },
    { word: "Avocado", story: "With Orchids. Spanish/Nahuatl from ahuacatl meaning testicle.", year: "1764", category: ["couplet", "food"], coupletId: "orchids-avocado", imageUrl: "https://i.pinimg.com/736x/ed/34/ce/ed34ced1216b6d01d62e006f2087f1b2.jpg" },
    { word: "Fungus", story: "With Sponge. From Greek sphongos (sponge) the Attic form of spongos.", year: "1527", category: ["couplet"], coupletId: "fungus-sponge", imageUrl: "https://cdn.cosmos.so/21607b94-6bf2-4772-96a5-d2302f00d10e?format=webp&w=1168" },
    { word: "Sponge", story: "With Fungus. From Greek sphongos (sponge).", year: "", category: ["couplet"], coupletId: "fungus-sponge", imageUrl: "https://cdn.cosmos.so/74b2b467-ff3e-423b-a010-58723fccccfe?format=webp&w=1168" },
    { word: "Chaos", story: "With Yawn. Greek khaos (abyss).", year: "1300s", category: ["couplet"], coupletId: "chaos-yawn", imageUrl: "" },
    { word: "Yawn", story: "With Chaos. From Greek root ghieh- to yawn. From khaos (abyss)", year: "", category: ["couplet"], coupletId: "chaos-yawn", imageUrl: "" },
    { word: "Canvas", story: "With Cannabis. Old French chanevaz (literally, made of hemp).", year: "1260", category: ["couplet"], coupletId: "canvas-cannabis", imageUrl: "" },
    { word: "Cannabis", story: "With Canvas. From Greek kannabis (hemp) a Scythian or Thracian word.", year: "1728", category: ["couplet"], coupletId: "canvas-cannabis", imageUrl: "https://pictura-prints.com/wp-content/uploads/2019/06/pcom-10177.jpg" },
    { word: "Gargoyle", story: "With Gargle. Possibly from garg (imitative of throat sounds) + goule (From Latin gula = throat).", year: "1200s", category: ["couplet"], coupletId: "gargoyle-gargle", imageUrl: "" },
    { word: "Gargle", story: "With Gargoyle. Old French gargole (throat).", year: "1527", category: ["couplet"], coupletId: "gargoyle-gargle", imageUrl: "" },

    // Proper Nouns
    { word: "Bougainvillaea", story: "French navigator Louis Bougainville posthumously.", year: "1849", category: ["proper-noun"], imageUrl: "https://www.lookandlearn.com/history-images/preview/M/M221/M221611_Louis-Antoine-de-Bougainville-French-admiral-and-explorer.jpg" },
    { word: "Dunce", story: "Follower of John Duns Scotus (c. 1265-1308), Scottish scholar of philosophy and theology; By 1520s, humanist reaction against medieval theology had singled him out as the type of the hairsplitting scholastic and it became a general term applied to obstinate philosophical opponents.", year: "1530", category: ["proper-noun"], imageUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQAfXQQDHT0zmxxMUU3C9b5x3LO0I9Quq9XzWr4HrRfkzV9nfMYO1tor_PJqsZQgWvSwhE9l45v1ETdWVFvGOzyAA" },
    { word: "Luddite", story: "The name taken by an organized band of weavers in Midlands and northern England who for about 5 years thereafter destroyed machinery, for fear it would deprive them of work. Supposedly they got it from Ned Ludd, a Leicestershire worker who in 1779 had smashed two machines in a rage.", year: "1811", category: ["proper-noun"], imageUrl: "https://www.worldhistory.org/img/r/p/1500x1500/17132.png.webp?v=1724660765-1677580446" },
    { word: "Sadism", story: "From French sadisme, from the name of Count Donatien A.F. de Sade (1740-1815) who was notorious for the cruel sexual practices described in his novels.", year: "1888", category: ["proper-noun"], imageUrl: "https://cdn.britannica.com/58/66758-050-7A02462F/Marquis-de-Sade.jpg" },
    { word: "Masochism", story: "From German Masochismus, coined by German neurologist Richard von Krafft-Ebing from name of Leopold von Sacher-Masoch (1836-1895), Austrian utopian socialist novelist who enshrined his submissive sexuality in 'Venus in Furs'.", year: "1883", category: ["proper-noun"], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Leopold_von_Sacher-Masoch%2C_portrait.jpg" },
    { word: "Sandwich", story: "Named after the John Montagu, the 4th Earl of Sandwich, who ate meat between bread while gambling.", year: "1762", category: ["proper-noun", "food"], imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/John_Montagu%2C_4._Earl_of_Sandwich.jpg/250px-John_Montagu%2C_4._Earl_of_Sandwich.jpg" }
    
];
